groups:
  - name: integration-server-destinations
    rules:
      - alert: DestinationDown
        expr: destination_health_status == 0
        for: 5m
        labels:
          severity: critical
          service: integration-server
        annotations:
          summary: "Destination {{ $labels.destination_name }} is down"
          description: "Destination {{ $labels.destination_name }} for organization {{ $labels.organization_id }} has been down for more than 5 minutes."

      - alert: DestinationDegraded
        expr: destination_health_status == 0.5
        for: 10m
        labels:
          severity: warning
          service: integration-server
        annotations:
          summary: "Destination {{ $labels.destination_name }} is degraded"
          description: "Destination {{ $labels.destination_name }} for organization {{ $labels.organization_id }} has been degraded for more than 10 minutes."

      - alert: HighDestinationErrorRate
        expr: rate(destination_errors_total[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
          service: integration-server
        annotations:
          summary: "High error rate for destination {{ $labels.destination_name }}"
          description: "Destination {{ $labels.destination_name }} has an error rate of {{ $value }} errors/second over the last 5 minutes."

      - alert: SlowDestinationResponse
        expr: histogram_quantile(0.95, rate(destination_request_duration_seconds_bucket[5m])) > 30
        for: 10m
        labels:
          severity: warning
          service: integration-server
        annotations:
          summary: "Slow response times for destination {{ $labels.destination_name }}"
          description: "95th percentile response time for destination {{ $labels.destination_name }} is {{ $value }}s, which exceeds the 30s threshold."

  - name: integration-server-cc-pairs
    rules:
      - alert: CCPairSyncFailed
        expr: increase(cc_pair_sync_attempts_total{status="error"}[1h]) >= 3
        for: 0m
        labels:
          severity: critical
          service: integration-server
        annotations:
          summary: "CC-Pair {{ $labels.cc_pair_id }} sync repeatedly failing"
          description: "CC-Pair {{ $labels.cc_pair_id }} ({{ $labels.connector_source }} -> {{ $labels.destination_name }}) has failed {{ $value }} times in the last hour."

      - alert: CCPairSyncSlow
        expr: histogram_quantile(0.95, rate(cc_pair_sync_duration_seconds_bucket[5m])) > 3600
        for: 15m
        labels:
          severity: warning
          service: integration-server
        annotations:
          summary: "CC-Pair {{ $labels.cc_pair_id }} sync is slow"
          description: "95th percentile sync duration for CC-Pair {{ $labels.cc_pair_id }} is {{ $value }}s ({{ $value | humanizeDuration }}), which exceeds the 1-hour threshold."

      - alert: CCPairNoRecentSync
        expr: time() - cc_pair_last_sync_timestamp > 86400
        for: 0m
        labels:
          severity: warning
          service: integration-server
        annotations:
          summary: "CC-Pair {{ $labels.cc_pair_id }} has not synced recently"
          description: "CC-Pair {{ $labels.cc_pair_id }} ({{ $labels.connector_source }} -> {{ $labels.destination_name }}) has not had a successful sync in over 24 hours."

      - alert: TooManyActiveSyncs
        expr: cc_pair_active_syncs > 10
        for: 5m
        labels:
          severity: warning
          service: integration-server
        annotations:
          summary: "Too many active syncs for organization {{ $labels.organization_id }}"
          description: "Organization {{ $labels.organization_id }} has {{ $value }} active syncs, which may indicate a bottleneck or stuck syncs."

  - name: integration-server-system
    rules:
      - alert: IntegrationServerDown
        expr: up{job="integration-server"} == 0
        for: 1m
        labels:
          severity: critical
          service: integration-server
        annotations:
          summary: "Integration Server is down"
          description: "The Integration Server API is not responding to health checks."

      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 0.9
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "High memory usage"
          description: "Memory usage is above 90% ({{ $value | humanizePercentage }}) for more than 5 minutes."

      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 10m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is above 80% ({{ $value }}%) for more than 10 minutes."

      - alert: DiskSpaceLow
        expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) < 0.1
        for: 5m
        labels:
          severity: critical
          service: system
        annotations:
          summary: "Low disk space"
          description: "Disk space is below 10% ({{ $value | humanizePercentage }}) on {{ $labels.mountpoint }}."
