global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Integration Server API
  - job_name: 'integration-server'
    static_configs:
      - targets: ['host.docker.internal:8000']  # Adjust port as needed
    metrics_path: '/metrics/prometheus'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # PostgreSQL Exporter (if using postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['host.docker.internal:9187']  # Uncomment if using postgres_exporter
    scrape_interval: 30s

  # Redis Exporter (if using redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['host.docker.internal:9121']  # Uncomment if using redis_exporter
    scrape_interval: 30s


