name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        ports:
          - 55432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: integration_server
        options: >-
          --health-cmd "pg_isready -U postgres" --health-interval 10s --health-timeout 5s --health-retries 5

      redis:
        image: redis:7-alpine
        ports:
          - 56379:6379
        options: >-
          --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v4
        with:
          # Only checkout what we need for CI
          sparse-checkout: |
            backend/
            tests/
            connectors/
            shared_configs/
            worker/
            web/src/
            web/package.json
            web/package-lock.json
            web/tsconfig.json
            web/tsconfig.node.json
            web/vite.config.ts
            web/vitest.setup.ts
            web/index.html
            pyproject.toml
            poetry.lock
            mypy.ini
            pytest.ini
            .github/
          sparse-checkout-cone-mode: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
          pip install --upgrade poetry

      - name: Cache Poetry virtualenvs
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: ${{ runner.os }}-poetry-

      - name: Install dependencies
        run: |
          poetry install --with dev

      - name: Lint (ruff)
        run: |
          poetry run ruff check .

      - name: Type check (mypy)
        run: |
          poetry run mypy .

      - name: Test
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 55432
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: integration_server
          REDIS_HOST: localhost
          REDIS_PORT: 56379
        run: |
          poetry run pytest -q 